version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: iomega/podp-api
    volumes:
      - ./data:/data
    environment:
       SHARED_TOKEN: ${SHARED_TOKEN:-ashdfjhasdlkjfhalksdjhflak}
       REDIS_URL: redis://redis:6379
       ZENODO_ACCESS_TOKEN: ${ZENODO_ACCESS_TOKEN}
       ZENODO_DEPOSITION_ID: ${ZENODO_DEPOSITION_ID}
       ELASTICSEARCH_URL: http://search:9200
       SLACK_TOKEN: ${SLACK_TOKEN}
       SLACK_CHANNEL: ${SLACK_CHANNEL}
    depends_on:
      - redis
      - search
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: app
    image: "iomega/paired-data-form"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - api
    ports:
      - "${PORT:-8443}:80"
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  search:
    image: elasticsearch:7.17.0
    volumes:
      - search:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      logger.level: warn
      cluster.routing.allocation.disk.threshold_enabled: 'false'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  redis:
  search:
